base-url: "https://clientcentral.io"
token: ""
button-ids:
  reassign-to-self: 187
  accept: 182
  decline: 183
  comment: 184
  complete: 17
  cancel-ticket: 180
  grab: 185
  send-to-internal-it-team: 121
  request-information: 178
  provide-information: 179
  suggest-solution: 181
ticket-priority:
  critical: 1
  high: 2
  medium: 3
  low: 4
  very-low: 33
ticket-status:
  in-progress: 2
  new: 1
  completed: 11
  cancelled: 12
ticket-workspace:
  managed-services: 25
user_ids:
  tihan-pelser: 14015
  thomas-scholtz: 14012
  marin-peroski: 11122
  tiaan-scheepers: 6